### PR TITLE
Add GitLab CI

### PR DESCRIPTION
**Pull request by sosiristseng**
This change adds a CI file for GitLab.

Edit: from https://discourse.julialang.org/t/pluto-pages-on-gitlab/62837

### CODE REVIEW

**Comment by pankgeorg** [comment]
Looks great! I have one question only:
You do use the cache but you have one cache per commit. Which scenario does this help?

**Comment by sosiristseng** [comment]
I took the example from the [GitLab CD/CI docs](https://docs.gitlab.com/ee/ci/caching/#share-caches-between-jobs-in-the-same-branch):

> Define a cache with the key: `${CI_COMMIT_REF_SLUG}` so that jobs of each branch always use the same cache.

And [the cache did hit](https://gitlab.com/sosiristseng/pluto-notebooks/-/jobs/1345294993) when the notebooks were not modified.

To sum up, it was one cache per branch (`REF`) rather than one cache per commit.

**Comment by pankgeorg** [comment]
Correct; it's per branch; but I think this is worse. What happens if you do change the notebooks within the same branch?

**Comment by sosiristseng** [comment]
I did a [small test](https://github.com/sosiristseng/pluto-notebooks/commit/fa9e9cfdec49524991ae07a11c83b2c2953a3c9b) and [here](https://gitlab.com/sosiristseng/pluto-notebooks/-/jobs/1347819109) were the CI/CD results.

The one `jl` file I modified did re-evaluate due to hash mismatch. The others were cached.

**Comment by fonsp** [comment]
I think this should be a separate repository, the template is meant to make it as simple as possible to get this running, and still I think that it is too difficult. A deployment file for another platform would be distracting, and confusing if you want to make changes.

**Comment by sosiristseng** [comment]
That's a good idea. I put GitHub and GitLab CI files together because I often mirror GitHub repos to GitLab. The CI/CD would run in both ways, albeit with some additional complexity indeed.

**Comment by fonsp** [comment]
https://github.com/JuliaPluto/static-export-template-gitlab

**Pull request closed without merging**
